### ISSUE TITLE
attempting to try this

### ISSUE THREAD

**Issue by protodmorgan** [yu-iskw/bigquery-to-datastore#1]
Maybe I am missing something, but when I try to run the job I'm getting this error:

(dfb1d562509e1bce): java.lang.NullPointerException
	at com.github.yuiskw.beam.TableRow2EntityFn.convertTableRowToEntity(TableRow2EntityFn.java:149)
	at com.github.yuiskw.beam.TableRow2EntityFn.processElement(TableRow2EntityFn.java:55)

**Comment by protodmorgan** [comment]
nevermind. issue is not enough coffee and forgot to update keycolumn.
